### ISSUE TITLE
Stone PHP SafeCrypt: Updated? Still recommended?

### ISSUE THREAD

**Issue by larrykluger** [StoneCypher/discuss#1]
Hi,

I want to securely data in a cookie using PHP. Do you still suggest using your Stone PHP SafeCrypt library? The original website appears to be offline, but I found a copy here:

https://web.archive.org/web/20080221185148/http://blog.sc.tri-bit.com/archives/101

Thanks and regards,
Larry

**Comment by StoneCypher** [comment]
It's still fine, but there are much stronger things since.

Encrypted data is, fundamentally, never actually secure, no matter how strong your thing is.  If it's in the cookie, it's crackable.  (If you can hash and compare, do that instead.)

Depending on how often you look inside the contents of that cookie, scrypt/bcrypt may be the correct path.  I don't have enough information yet to comment.

**Comment by StoneCypher** [comment]
If you'll tell me more about what you're doing, and your actual needed level of security, maybe I can say something more concrete?

The answer is very different for "I'm trying to make it not fun to cheat at high scores on this game" and for "I'm building a spy network that ten thousand lives rely on."

**Comment by larrykluger** [comment]
Hi John,

Thanks for the info. I was first trying to avoid a db and store in the
cookie instead. But after further reflection, I realized that I would
already need a db for other parts of the project.

So instead of encryption, I'll store a random string in the cookie and use
it as a key to lookup the data in the db.

Thanks and regards,
Larry

**Comment by StoneCypher** [comment]
Best of luck to you then.

Closing as resolved.
